.TH "msgbuf" 3 "Sábado, 6 de Julio de 2019" "Proyecto de Sistemas Operativos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msgbuf \- Contiene información del número de autos que pasan por una vía\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <defines\&.h>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "long \fBmtype\fP"
.br
.ti -1c
.RI "unsigned short \fBcar\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Contiene información del número de autos que pasan por una vía\&. 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proyecto de Sistemas Operativos del código fuente\&.
