.TH "defines.h" 3 "Lunes, 8 de Julio de 2019" "Proyecto de Sistemas Operativos - Semáforos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
defines.h \- Definición de constantes\&.  

.SH SYNOPSIS
.br
.PP
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBSHARED_FILE\fP   '/bin/ls'"
.br
.ti -1c
.RI "#define \fBSHARED_NUM\fP   111"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición de constantes\&. 


.PP
\fBAutor:\fP
.RS 4
Angel J\&. España B\&. 
.PP
Adriana P\&. Daboin M\&. 
.RE
.PP

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proyecto de Sistemas Operativos - Semáforos del código fuente\&.
