.TH "membuf" 3 "Lunes, 8 de Julio de 2019" "Proyecto de Sistemas Operativos - Semáforos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
membuf \- Contiene información del número de autos que pasan por una vía, además de contar la cantidad de procesos activos\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shared_mem\&.h>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "unsigned short \fBcars_1\fP"
.br
.ti -1c
.RI "unsigned short \fBcars_2\fP"
.br
.ti -1c
.RI "unsigned short \fBcars_3\fP"
.br
.ti -1c
.RI "unsigned short \fBcars_4\fP"
.br
.ti -1c
.RI "unsigned short \fBtotal_cars_1\fP"
.br
.ti -1c
.RI "unsigned short \fBtotal_cars_2\fP"
.br
.ti -1c
.RI "unsigned short \fBtotal_cars_3\fP"
.br
.ti -1c
.RI "unsigned short \fBtotal_cars_4\fP"
.br
.ti -1c
.RI "unsigned short \fBstop\fP"
.br
.ti -1c
.RI "unsigned short \fBprocess_counter\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Contiene información del número de autos que pasan por una vía, además de contar la cantidad de procesos activos\&. 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proyecto de Sistemas Operativos - Semáforos del código fuente\&.
